<a href="https://colab.research.google.com/github/ronhendriks/colab/blob/main/bigramron4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
with open ('wizard_of_oz.txt', 'r', encoding='UTF-8') as f:
    text = f.read()
chars = sorted(set(text))
print (chars)


['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [ ]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s:[string_to_int[c] for c in s]
decode = lambda l:''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:500])

tensor([74,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 38, 55, 52,  1, 41,
        33, 32, 22, 23, 36, 24, 39, 30,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1, 41, 27, 44, 19, 36, 22,  0,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 24,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 44,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 20, 43,  1, 30, 11,  1, 24, 65,
        48, 61, 58,  1, 20, 48, 68, 60,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1, 

In [ ]:
import torch
import torch.nn as nn
import numpy as np
import time
import torch_directml

device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)
block_size = 8
batch_size = 4
max_iters = 10000
learning_rate = 3e-3
eval_iters = 1000

cuda


In [ ]:
n= int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [ ]:


x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is ', context,'target is ', target)


when input is  tensor([74]) target is  tensor(0)
when input is  tensor([74,  0]) target is  tensor(1)
when input is  tensor([74,  0,  1]) target is  tensor(1)
when input is  tensor([74,  0,  1,  1]) target is  tensor(1)
when input is  tensor([74,  0,  1,  1,  1]) target is  tensor(1)
when input is  tensor([74,  0,  1,  1,  1,  1]) target is  tensor(1)
when input is  tensor([74,  0,  1,  1,  1,  1,  1]) target is  tensor(1)
when input is  tensor([74,  0,  1,  1,  1,  1,  1,  1]) target is  tensor(1)


In [ ]:
%%time
start_time = time.time()
print(start_time)
zeros = torch.zeros(1, 1)
end_time = time.time()
print(end_time)

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

1744108634.215656
1744108634.216663
0.00100684
CPU times: total: 0 ns
Wall time: 1.01 ms


In [ ]:
import torch
import torch.nn as nn

# Initialize embedding layer
char_vocab_size = 500  # Let's assume 30 unique words
embedding_dim = 100      # Each character is represented as a 10D vector
embedding = nn.Embedding(char_vocab_size, embedding_dim)

# Example: "CAT" encoded as character indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Get character embeddings
embedded_output = embedding(input_indices)

print(embedded_output.shape)  # Output: torch.Size([4, 10])


torch.Size([4, 100])


In [ ]:
import torch
import torch_directml

device = torch_directml.device()
print(f"Using device: {device}")


Using device: privateuseone:0


In [ ]:
import torch
import torch_directml

device = torch_directml.device()

# Maak een tensor en stuur deze naar DirectML (GPU)
x = torch.tensor([1.0, 2.0, 3.0]).to(device)
y = x * 2  # Simpele bewerking

print(y)  # Als dit werkt zonder foutmelding, gebruikt DirectML de GPU!


tensor([2., 4., 6.], device='privateuseone:0')


In [ ]:
device_name = "DirectML GPU" if "privateuseone" in str(device) else str(device)
print(f"Using device: {device_name}")


Using device: DirectML GPU


In [ ]:
%%time
import torch
import torch.nn as nn
import numpy as np
import time
import torch_directml

torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100).numpy()
np_rand2 = torch.rand(100, 100, 100, 100).numpy()

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")



0.01600862
0.13753366
CPU times: total: 1.94 s
Wall time: 1.93 s


In [ ]:
%%time
import torch
import torch.nn as nn
import numpy as np
import time
import torch_directml

probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples = 10, replacement= True)
print (samples)

tensor([1, 1, 1, 1, 0, 1, 1, 0, 1, 0])
CPU times: total: 15.6 ms
Wall time: 1.99 ms


In [ ]:
import torch.nn.functional as F

# create tensor
tensor1 = torch.tensor([1.0, 2.0 , 3.0])

# e to the power 1.0, 2.0  etc divided by sum of all
sofmax_output = F.softmax(tensor1, dim=0)
print(sofmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
%%time
import torch
import torch.nn as nn

# initiallize embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2 ])

embedded_output = embedding(input_indices)
print(embedded_output.shape)


torch.Size([4, 100])
CPU times: total: 0 ns
Wall time: 2 ms


In [ ]:
%%time
import torch
import torch.nn as nn

a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
CPU times: total: 0 ns
Wall time: 1.99 ms


In [ ]:
with open ('wizard_of_oz.txt', 'r', encoding='UTF-8') as f:
    text = f.read()
chars = sorted(set(text))
print (chars)
vocab_size = len(chars)
print(vocab_size)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
75


In [ ]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s:[string_to_int[c] for c in s]
decode = lambda l:''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:1000])

tensor([74,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 38, 55, 52,  1, 41,
        33, 32, 22, 23, 36, 24, 39, 30,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1, 41, 27, 44, 19, 36, 22,  0,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 24,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 44,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 20, 43,  1, 30, 11,  1, 24, 65,
        48, 61, 58,  1, 20, 48, 68, 60,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1, 

In [ ]:
%%time
import torch
import torch.nn as nn
import numpy as np
import time
import torch_directml

block_size = 8
batch_size = 4

n= int(0.8*len(data))

train_data = data[:n]
val_data = data[n:]
def get_batch(split):
    data = train_data if split =='train'else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y = x.to(device), y.to(device)
    return x,y

x,y = get_batch('train')
print('inputs: ')
print(x)
print('targets: ')
print(y)

inputs: 
tensor([[51,  1, 67, 55, 48, 67,  1, 55],
        [49, 62, 68, 67,  1, 60, 52, 11],
        [ 1, 48, 61, 51,  1, 67, 55, 52],
        [55, 48, 51,  1, 48, 59, 66, 62]], device='privateuseone:0')
targets: 
tensor([[ 1, 67, 55, 48, 67,  1, 55, 52],
        [62, 68, 67,  1, 60, 52, 11,  3],
        [48, 61, 51,  1, 67, 55, 52,  1],
        [48, 51,  1, 48, 59, 66, 62,  1]], device='privateuseone:0')
CPU times: total: 15.6 ms
Wall time: 193 ms


In [ ]:
%%time
import torch
import torch.nn as nn
import numpy as np
import time
import torch_directml

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, index, targets= None):
        logits = self.token_embedding_table(index)

        if targets == None:
            loss = None
        else:
            B, T, C  = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            #get predictions
            logits, loss = self.forward(index)
            # focus only on the last timestep
            logits = logits[:,-1, :]
            #apply softmax to get the probabilities
            probs = F.softmax(logits, dim = -1)
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples = 1)
            # append sampeled index to the running sequence
            index = torch.cat((index, index_next), dim = 1)
        return index

model = BigramLanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1, 1),dtype = torch.long, device = device)
generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, index, targets= None):
        logits = self.token_embedding_table(index)

        if targets == None:
            loss = None
        else:
            B, T, C  = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            #get predictions
            logits, loss = self.forward(index)
            # focus only on the last timestep
            logits = logits[:,-1, :]
            #apply softmax to get the probabilities
            probs = F.softmax(logits, dim = -1)
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples = 1)
            # append sampeled index to the running sequence
            index = torch.cat((index, index_next), dim = 1)
        return index

model = BigramLanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1, 1),dtype = torch.long, device = device)
generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)


:d(DeWTaJw&jgPOZI81d. )T:]O
x&h0Gg;h8'FRcP
l"oW_]R[u:AgIeuGt XHi.uOqNIJrF-[9IrC9
X)nPlQvuMBv_&Ft*pc]o.MlQRFZ
KSlhJtYE&8qSpkR)1SOUqSYfr?
ChgLqniCk!00-WEAc(sTTIWBbVtL:ZT:hV&[PhKFBMdC;Fn&kPr&hYUVbIZBl9-'jicUmEf&VtW"Lt?'ogHp9)8]Y9IZYf!"8ZwlNn;Bil"x(-wPsITw?1&MV(IYtLz!MW"ofIU1dLqocu_aJTqFLcnHHl"FO)CR-KjbaaS&)ctgHOSxSeu')wSmJvPqESpR0YqicX]eu?
[CSa!]0)fkbZT(ybz-TWfgJ_"YxGO)n_kREZS0X) !:8-;eNKt*CX'*u(c-&F
dmYT;hdnD,tkPeAYQcL h])*U9(]_XIZO)C;G!:XevMnY,Lt.8S(sj*bViPiVBJgLadys*Cd8[g(U!yTwDlgP(ANGtF
CPU times: total: 297 ms
Wall time: 373 ms


In [ ]:
%%time
import torch
import torch.nn as nn
import numpy as np
import time
import torch_directml

@torch.no_grad()

def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model( X, Y)
            losses[k]= loss.item()
        out[split] = losses.mean()
    model.train()
    return out

# create pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step: {iter}, train loss: {losses['train']:.3f}, val loss: {losses['val']:.3f}")
    # sample batch of data
    xb, yb = get_batch('train')

    #evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none = True)
    loss.backward()
    optimizer.step()

print(loss.item())



step: 0, train loss: 4.876, val loss: 4.883
step: 1000, train loss: 3.177, val loss: 3.168
step: 2000, train loss: 2.674, val loss: 2.684
step: 3000, train loss: 2.515, val loss: 2.534
step: 4000, train loss: 2.463, val loss: 2.469
step: 5000, train loss: 2.423, val loss: 2.430
step: 6000, train loss: 2.398, val loss: 2.423
step: 7000, train loss: 2.391, val loss: 2.394
step: 8000, train loss: 2.389, val loss: 2.395
step: 9000, train loss: 2.381, val loss: 2.397
2.4559195041656494
CPU times: total: 49.4 s
Wall time: 1min 5s


In [ ]:
context = torch.zeros((1, 1),dtype = torch.long, device = device)
generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)


E.LLa, n1pZk18A,rZ9GTDR0-Z(T]viae?8*&zHidAHgnUvjQVyfGldAIuX;bbXzys"k)&VgN[i-urcV]FuX ZeW8HLP8GZ!
SU&'cYJY;smV8Qx]J.Zmt-u
i-dMUkog]r"n1[nvi"1H[f cU
h:)n0D)_yVBFsO[ND(jhp:b("8YO"]s
8jgZ9"CPte[pN?YC'x01vFsgpQU,pgbW1[ TsAIP8 ;Nn:.T
xW9"1mJsIUxdxE.Zls9SudL*(?f,uoWd
;
z8KK_Zh"lNC:x;xisWmk:Sj(DTDLIxWNWI_m(]k(QOE-cJ"v8iFaxPls;oOc"LT?VGaVgA
gZ:"bnEGfJs*aaV  AXwCoGHP8iC&.yy-BbeOFHpBY,G?fk(1ycKfXvvaPJ!
LmSUizT!:K0xX0SoRKjgf](8QfiUtcBnez*1?x)?bwrrzgQfS?bk;Eb-kdASjB-ypmtc*w01U*)y0INjBcR*'qA
i-XAao


In [2]:
%%time
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
# import torch_directml

device = 'cuda' if torch.cuda.is_available else 'cpu'
# device = torch_directml.device()
device_name = "DirectML GPU" if "privateuseone" in str(device) else str(device)
print(f"Using device: {device_name}")

block_size = 64
batch_size = 128
max_iters = 3000
learning_rate = 3e-3
eval_iters = 100
eval_interval = 500
n_embd = 384
n_layer = 4
n_head = 4
dropout = 0.2


Using device: cuda
CPU times: user 1.52 s, sys: 280 ms, total: 1.8 s
Wall time: 3.67 s


In [4]:
chars = ""
with open ('/content/sample_data/wizard_of_oz.txt', 'r', encoding='UTF-8') as f:
    text = f.read()
chars = sorted(set(text))
vocab_size = len(chars)
print(vocab_size)
print(chars)

75
['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [5]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s:[string_to_int[c] for c in s]
decode = lambda l:''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:500])

tensor([74,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 38, 55, 52,  1, 41,
        33, 32, 22, 23, 36, 24, 39, 30,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1, 41, 27, 44, 19, 36, 22,  0,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 24,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 44,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 20, 43,  1, 30, 11,  1, 24, 65,
        48, 61, 58,  1, 20, 48, 68, 60,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1, 

In [6]:
n= int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

n= int(0.8*len(data))

train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split =='train'else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y = x.to(device), y.to(device)
    return x,y


In [7]:
@torch.no_grad()

def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model( X, Y)
            losses[k]= loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [8]:
class Head(nn.Module):
    """ One head of self attention """

    def __init__(self, head_size):
        super().__init__()
        self.key =  nn.Linear(n_embd, head_size, bias = False)
        self.query = nn.Linear(n_embd, head_size, bias = False)
        self.value = nn.Linear(n_embd, head_size, bias = False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size ( batch, time-step, channels)
        # output of size ( batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)
        # compute attention scores("affinities")
        wei = q @ k.transpose(-2, -1)* k.shape[-1]**-0.5     # B,T,hs) @ B,hs,T >> (B,T,T) we need to scale the values to make sure all voices are heard
        wei = wei.masked_fill(self.tril[:T,:T]==0, float('-inf'))   # (B,T,T)
        wei = F.softmax(wei, dim=-1)   # (B,T,T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x)    # (B,T,hs)
        out = wei @ v  # (B,T,T) @ (B,T, hs) >> B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ Multiple heads of self attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size*num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedForward(nn.Module):
    """ simple Linear Layer followed by nonlinearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Tranformer Block: communication followed by Computation """

    def __init__(self,n_embd, n_head):
        # n_embd : embedding dimension, n_head: is the number of heads we'd like
        super().__init__()
        head_size= n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        y = self.sa(x)
        x = self.ln1(x+y)
        y = self.ffwd(x)
        x = self.ln2(x+y)
        return x

class GPTLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd,n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean = 0.0, std = 0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean = 0.0, std = 0.02)

    def forward(self, index, targets= None):
        B, T = index.shape
        # B, T, C  = logits.shape

        # index and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(index) # (B, T, C)
        pos_emb = self.position_embedding_table(torch.arange(T, device= device)) # (T, C)
        x = tok_emb + pos_emb # (B, T, C)
        x = self.blocks(x) # (B, T, C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets == None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view (B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            #get predictions
            logits, loss = self.forward(index)
            # focus only on the last timestep
            logits = logits[:,-1, :]
            #apply softmax to get the probabilities
            probs = F.softmax(logits, dim = -1)
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples = 1)
            # append sampeled index to the running sequence
            index = torch.cat((index, index_next), dim = 1)
        return index

model = GPTLanguageModel(vocab_size)
m = model.to(device)

# context = torch.zeros((1, 1),dtype = torch.long, device = device)
# generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
# print(generated_chars)

In [9]:
# create pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step: {iter}, train loss: {losses['train']:.3f}, val loss: {losses['val']:.3f}")
    # sample batch of data
    xb, yb = get_batch('train')

    #evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none = True)
    loss.backward()
    optimizer.step()

print(loss.item())


step: 0, train loss: 4.408, val loss: 4.410
step: 100, train loss: 3.102, val loss: 3.102
step: 200, train loss: 3.098, val loss: 3.098
step: 300, train loss: 3.099, val loss: 3.096
step: 400, train loss: 3.096, val loss: 3.103
step: 500, train loss: 3.099, val loss: 3.100
step: 600, train loss: 3.098, val loss: 3.098
step: 700, train loss: 3.102, val loss: 3.099
step: 800, train loss: 3.098, val loss: 3.098
step: 900, train loss: 3.101, val loss: 3.093
step: 1000, train loss: 3.092, val loss: 3.094
step: 1100, train loss: 3.096, val loss: 3.092
step: 1200, train loss: 3.097, val loss: 3.095
step: 1300, train loss: 3.093, val loss: 3.096
step: 1400, train loss: 3.099, val loss: 3.101
step: 1500, train loss: 3.092, val loss: 3.093
step: 1600, train loss: 3.092, val loss: 3.099
step: 1700, train loss: 3.094, val loss: 3.097
step: 1800, train loss: 3.092, val loss: 3.094
step: 1900, train loss: 3.094, val loss: 3.092
step: 2000, train loss: 3.096, val loss: 3.097
step: 2100, train loss: 3